const states = [
  {
    slug: 'uttar-pradesh', name: 'Uttar Pradesh', region: 'North', capital: 'Lucknow',
    blurb: 'A sweep of northern plains shaped by the sacred basins of the Ganges and Yamuna, home to colossal Mughal stone structures, centuries of Awadhi culinary arts, and the ancient riverside steps of Varanasi.',
    cover_url: '/assets/place-taj.jpg',
    highlights: [
      'Observing the precise architectural symmetry of the Taj Mahal at dawn',
      'Witnessing the evening Ganga Aarti fire ceremony at Varanasi\'s waterfront',
      'Exploring the ancient ruins of Ashokan pillars and monasteries in Sarnath',
      'Sampling Awadhi culinary specialties and walking through the corridors of Lucknow\'s Imambaras',
    ],
    best_time: 'October to March (cool, dry winter months)',
    popular_cities: [
      { name: 'Agra',    note: 'Taj Mahal, Agra Fort, Fatehpur Sikri', map_link: 'https://maps.google.com/?q=Agra' },
      { name: 'Varanasi',note: 'Ghats, Kashi Vishwanath, Sarnath',    map_link: 'https://maps.google.com/?q=Varanasi' },
      { name: 'Lucknow', note: 'Bara Imambara, Chhota Imambara, Hazratganj', map_link: 'https://maps.google.com/?q=Lucknow' },
      { name: 'Ayodhya', note: 'Ram Janmabhoomi and Sarayu river ghats',    map_link: 'https://maps.google.com/?q=Ayodhya' },
    ],
  },
  {
    slug: 'rajasthan', name: 'Rajasthan', region: 'West', capital: 'Jaipur',
    blurb: 'A western desert region defined by yellow and pink sandstone fortresses, palaces built on lakes, and historic trading settlements along the Thar.',
    cover_url: '/assets/place-hawamahal.jpg',
    highlights: [
      'Exploring the double-walled stone battlements of Amber and Mehrangarh Forts',
      'Riding camel trails across the dunes of the Thar Desert in Jaisalmer',
      'Boating past the historic lake palaces of Udaipur\'s Lake Pichola',
      'Walking through the Havelis and frescoed courtyards of the Shekhawati region',
    ],
    best_time: 'October to March (avoid the hot desert summer)',
    popular_cities: [
      { name: 'Jaipur',   note: 'Hawa Mahal, City Palace, Amber Fort', map_link: 'https://maps.google.com/?q=Jaipur' },
      { name: 'Udaipur',  note: 'Lake Pichola, City Palace, Sajjangarh', map_link: 'https://maps.google.com/?q=Udaipur' },
      { name: 'Jaisalmer',note: 'Golden Fort, Sam sand dunes, Jain temples',     map_link: 'https://maps.google.com/?q=Jaisalmer' },
      { name: 'Jodhpur',  note: 'Mehrangarh Fort, blue old town, Clock Tower', map_link: 'https://maps.google.com/?q=Jodhpur' },
    ],
  },
  {
    slug: 'kerala', name: 'Kerala', region: 'South', capital: 'Thiruvananthapuram',
    blurb: 'A coastal strip in the south flanked by the Western Ghats, featuring palm-lined canals, spice gardens, and kathakali performance traditions.',
    cover_url: '/assets/place-backwaters.jpg',
    highlights: [
      'Cruising the waterways of Alappuzha on a traditional thatched house boat',
      'Trekking through the misty spice gardens and tea estates of Munnar',
      'Watching Kathakali dance dramas and Kalaripayattu martial art demonstrations',
      'Walking past the historic Chinese fishing nets in Fort Kochi\'s harbor',
    ],
    best_time: 'September to March (post-monsoon green landscape)',
    popular_cities: [
      { name: 'Kochi',    note: 'Fort Kochi, Chinese nets, Mattancherry', map_link: 'https://maps.google.com/?q=Kochi' },
      { name: 'Alappuzha',note: 'Canals, houseboats, Vembanad Lake',   map_link: 'https://maps.google.com/?q=Alappuzha' },
      { name: 'Munnar',   note: 'Tea gardens, Eravikulam Park, Mattupetty',   map_link: 'https://maps.google.com/?q=Munnar' },
      { name: 'Thekkady', note: 'Periyar Wildlife Sanctuary, spice walks',   map_link: 'https://maps.google.com/?q=Thekkady' },
    ],
  },
  {
    slug: 'ladakh', name: 'Ladakh', region: 'North', capital: 'Leh',
    blurb: 'A trans-Himalayan desert region of high-altitude gravel valleys, rocky passes, and stone monasteries situated along blue lakes.',
    cover_url: '/assets/place-ladakh.jpg',
    highlights: [
      'Watching the water colors shift under the sun at Pangong Lake',
      'Listening to morning chants at Thiksey and Hemis monasteries',
      'Crossing Khardung La, a high motorable mountain pass',
      'Exploring the cold dunes and Bactrian camel trails in Nubra Valley',
    ],
    best_time: 'May to September (clear roads and pleasant temperatures)',
    popular_cities: [
      { name: 'Leh',         note: 'Leh Palace, Shanti Stupa, main bazaar', map_link: 'https://maps.google.com/?q=Leh' },
      { name: 'Nubra Valley',note: 'Hunder dunes, Diskit Monastery',        map_link: 'https://maps.google.com/?q=Nubra+Valley' },
      { name: 'Pangong Tso', note: 'High-altitude lake on the eastern border', map_link: 'https://maps.google.com/?q=Pangong+Tso' },
      { name: 'Kargil',      note: 'Drass valley, Suru river, war memorial', map_link: 'https://maps.google.com/?q=Kargil' },
    ],
  },
  {
    slug: 'tamil-nadu', name: 'Tamil Nadu', region: 'South', capital: 'Chennai',
    blurb: 'A southern coastal cradle of Dravidian history, marked by soaring temple gateway towers, granite carvings, and bronze-casting workshops.',
    cover_url: '/assets/place-meenakshi.jpg',
    highlights: [
      'Climbing the gateway towers of Madurai\'s Meenakshi Amman Temple',
      'Tracing ancient Pallava rock carvings by the sea in Mamallapuram',
      'Riding the Nilgiri Mountain Railway steam toy train up to Ooty',
      'Visiting the French Quarter and the Matrimandir dome near Pondicherry',
    ],
    best_time: 'November to February (dry interior, cool breezes)',
    popular_cities: [
      { name: 'Chennai',        note: 'Marina Beach, Kapaleeshwarar Temple, Fort St George', map_link: 'https://maps.google.com/?q=Chennai' },
      { name: 'Madurai',        note: 'Meenakshi Temple, Thirumalai Nayak Palace',    map_link: 'https://maps.google.com/?q=Madurai' },
      { name: 'Mahabalipuram',  note: 'Shore Temple, Five Rathas, rock carvings',         map_link: 'https://maps.google.com/?q=Mahabalipuram' },
      { name: 'Ooty',           note: 'Nilgiri toy train, botanical gardens, lake',   map_link: 'https://maps.google.com/?q=Ooty' },
    ],
  },
  {
    slug: 'maharashtra', name: 'Maharashtra', region: 'West', capital: 'Mumbai',
    blurb: 'A western state spanning Deccan plateaus and coastal ports, containing ancient rock-cut Buddhist caves and stone fortresses.',
    cover_url: '/assets/place-gateway.jpg',
    highlights: [
      'Walking past the Art Deco facades of Mumbai\'s Marine Drive',
      'Viewing the ancient Buddhist mural paintings inside the Ajanta Caves',
      'Trekking to historical Maratha fortresses like Raigad and Pratapgad',
      'Exploring the rock-cut monolithic structure of Ellora\'s Kailash Temple',
    ],
    best_time: 'October to February (cool weather, lush green hills)',
    popular_cities: [
      { name: 'Mumbai',     note: 'Gateway, Colaba Causeway, Elephanta Caves', map_link: 'https://maps.google.com/?q=Mumbai' },
      { name: 'Aurangabad', note: 'Base for Ajanta and Ellora Cave complexes',       map_link: 'https://maps.google.com/?q=Aurangabad' },
      { name: 'Pune',       note: 'Aga Khan Palace, Shaniwar Wada fort ruins', map_link: 'https://maps.google.com/?q=Pune' },
      { name: 'Lonavala',   note: "Karla Caves, Bhushi Dam, monsoon viewpoints", map_link: 'https://maps.google.com/?q=Lonavala' },
    ],
  },
  {
    slug: 'west-bengal', name: 'West Bengal', region: 'East', capital: 'Kolkata',
    blurb: 'An eastern territory extending from the delta paths of the Sundarbans to Himalayan tea estates, rooted in colonial architecture and literary movements.',
    cover_url: '/assets/place-victoria.jpg',
    highlights: [
      'Visiting the Victoria Memorial and riding historic hand-pulled trams in Kolkata',
      'Watching the sunrise over Tiger Hill in the Himalayan town of Darjeeling',
      'Taking a boat safari through the mangrove channels of the Sundarbans',
      'Exploring Rabindranath Tagore\'s Visva-Bharati university in Shantiniketan',
    ],
    best_time: 'October to March (post-monsoon cooling, clear skies)',
    popular_cities: [
      { name: 'Kolkata',      note: 'Victoria Memorial, Indian Museum, Howrah Bridge', map_link: 'https://maps.google.com/?q=Kolkata' },
      { name: 'Darjeeling',   note: 'Himalayan Railway, tea gardens, Tiger Hill',  map_link: 'https://maps.google.com/?q=Darjeeling' },
      { name: 'Sundarbans',   note: 'Mangrove forests, tiger reserve, delta cruises',  map_link: 'https://maps.google.com/?q=Sundarbans+National+Park' },
      { name: 'Shantiniketan',note: "Visva-Bharati, local Baul music, Kopai river",        map_link: 'https://maps.google.com/?q=Shantiniketan' },
    ],
  },
  {
    slug: 'himachal-pradesh', name: 'Himachal Pradesh', region: 'North', capital: 'Shimla',
    blurb: 'A northern mountain state of pine forests, snowy valleys, and towns that host the Tibetan government-in-exile.',
    cover_url: '/assets/place-shimla.jpg',
    highlights: [
      'Riding the narrow-gauge Kalka-Shimla toy train through the hills',
      'Visiting Tibetan temples and libraries in McLeod Ganj',
      'Hiking the high pass trail towards the cold desert of Lahaul and Spiti',
      'Paragliding over the landing site at Bir-Billing',
    ],
    best_time: 'March to June (pleasant summer) or December to February (snow)',
    popular_cities: [
      { name: 'Shimla',      note: 'The Mall Road, Viceregal Lodge, Ridge', map_link: 'https://maps.google.com/?q=Shimla' },
      { name: 'Manali',      note: 'Hadimba Temple, Solang Valley, Rohtang Pass',   map_link: 'https://maps.google.com/?q=Manali' },
      { name: 'Dharamshala', note: 'McLeod Ganj, Bhagsunag Falls, cricket stadium', map_link: 'https://maps.google.com/?q=Dharamshala' },
      { name: 'Spiti',       note: 'Key Monastery, Kaza town, Pin Valley',   map_link: 'https://maps.google.com/?q=Spiti+Valley' },
    ],
  },
  {
    slug: 'karnataka', name: 'Karnataka', region: 'South', capital: 'Bengaluru',
    blurb: 'A southern region of high plateaus and coffee-growing hills, containing the stone ruins of the Vijayanagara Empire.',
    cover_url: '/assets/place-hampi.jpg',
    highlights: [
      'Walking through the stone carvings and structural ruins of Hampi',
      'Viewing the Mysore Palace architecture during the evening illumination',
      'Staying at local coffee plantation homesteads in Coorg',
      'Viewing the giant monolithic statue of Gomateshwara in Shravanabelagola',
    ],
    best_time: 'October to March (mild temperatures across most regions)',
    popular_cities: [
      { name: 'Bengaluru', note: 'Cubbon Park, Vidhana Soudha, tech parks',      map_link: 'https://maps.google.com/?q=Bengaluru' },
      { name: 'Mysuru',    note: 'Mysore Palace, Chamundi Hills, Zoo',   map_link: 'https://maps.google.com/?q=Mysuru' },
      { name: 'Hampi',     note: 'Vijayanagara ruins, Virupaksha, Vittala temple',    map_link: 'https://maps.google.com/?q=Hampi' },
      { name: 'Coorg',     note: 'Coffee plantations, Abbey Falls, Madikeri',    map_link: 'https://maps.google.com/?q=Coorg' },
    ],
  },
  {
    slug: 'goa', name: 'Goa', region: 'West', capital: 'Panaji',
    blurb: 'A small western coastal state featuring historic Portuguese churches, spice plantations, and crescent-shaped sandy bays.',
    cover_url: '/assets/place-goa.jpg',
    highlights: [
      'Walking past the pastel-colored villas of Panaji\'s Latin Quarter',
      'Visiting 16th-century churches and structural ruins in Old Goa',
      'Kayaking along the sheltered waters of Palolem Beach in South Goa',
      'Tasting locally distilled feni at a spice plantation in Ponda',
    ],
    best_time: 'November to February (dry winter season)',
    popular_cities: [
      { name: 'Panaji',    note: 'Fontainhas Latin quarter, Mandovi riverfront', map_link: 'https://maps.google.com/?q=Panaji' },
      { name: 'Old Goa',   note: 'Basilica of Bom Jesus, Sé Cathedral',       map_link: 'https://maps.google.com/?q=Old+Goa' },
      { name: 'Calangute', note: 'Central beach markets and dynamic coastline',    map_link: 'https://maps.google.com/?q=Calangute' },
      { name: 'Palolem',   note: 'Crescent bay, kayaking, wooden beach huts', map_link: 'https://maps.google.com/?q=Palolem' },
    ],
  },
  {
    slug: 'uttarakhand', name: 'Uttarakhand', region: 'North', capital: 'Dehradun',
    blurb: 'A northern state at the headwaters of the Ganges, featuring deep river valleys, high-altitude meadows, and mountain trekking centers.',
    cover_url: '/assets/place-rishikesh.jpg',
    highlights: [
      'Walking the pedestrian suspension bridges over the Ganges in Rishikesh',
      'Trekking through pine forests and alpine meadows in Haridwar district',
      'Searching for wildlife in the grasslands of Jim Corbett National Park',
      'Boating on the volcanic lake of Nainital',
    ],
    best_time: 'March to June and September to November (avoid heavy monsoon)',
    popular_cities: [
      { name: 'Rishikesh', note: 'Yoga centers, Laxman Jhula, Ganga aarti', map_link: 'https://maps.google.com/?q=Rishikesh' },
      { name: 'Haridwar',  note: 'Har Ki Pauri ghats, pilgrim markets', map_link: 'https://maps.google.com/?q=Haridwar' },
      { name: 'Nainital',  note: 'Naini Lake, Mall Road, high-altitude views', map_link: 'https://maps.google.com/?q=Nainital' },
      { name: 'Mussoorie', note: 'Kempty Falls, Lal Tibba, colonial walks', map_link: 'https://maps.google.com/?q=Mussoorie' },
    ],
  },
];

const places = [
  {
    slug: 'taj-mahal', name: 'Taj Mahal', state_slug: 'uttar-pradesh', state_name: 'Uttar Pradesh',
    city: 'Agra', category: 'Heritage', image_url: '/assets/place-taj.jpg',
    tagline: 'A study in absolute Mughal symmetry, where translucent Makrana marble absorbs and mirrors the shifting pastel light of the Yamuna sky.',
    description: 'Rising from the banks of the Yamuna River, the Taj Mahal is the apex of Mughal architectural genius. Completed in 1648 as a mausoleum for Mumtaz Mahal by Emperor Shah Jahan, it is a masterclass in geometric balance and architectural precision. The structure is constructed entirely of white Makrana marble, which is hand-carved and inlaid with intricate floral scrollwork composed of semi-precious stones—jasper, lapis lazuli, jade, and carnelian. Under the changing skies, the dome shifts dynamically in hue, glowing a soft amber-pink at dawn, gleaming white at midday, and reflecting a cool, silver-blue during full moons.',
    best_time: 'October to March', timings: 'Sunrise to sunset (closed Fridays)',
    entry_fee: '₹50 (Indian) · ₹1,100 (Foreign)', map_link: 'https://maps.google.com/?q=Taj+Mahal+Agra',
    nearby: ['Agra Fort', 'Mehtab Bagh', "Itmad-ud-Daulah's Tomb"],
    trivia: "The Taj Mahal's marble shifts color depending on the time of day: it glows a soft pinkish-gold at dawn, shines bright white in the afternoon sun, and looks like a floating silver orb under a full moon.",
    travel_tip: "Arrive at the Eastern Gate by 5:30 AM to catch the first light. The morning mist over the Yamuna River makes for a surreal, crowd-free photography session."
  },
  {
    slug: 'varanasi-ghats', name: 'Varanasi Ghats', state_slug: 'uttar-pradesh', state_name: 'Uttar Pradesh',
    city: 'Varanasi', category: 'Religious', image_url: '/assets/place-varanasi.jpg',
    tagline: 'A sacred waterfront of stone steps where life, death, and devotional fire converge along the sweeping curve of the Ganges.',
    description: 'Varanasi, or Kashi, is a spiritual landscape carved out over millennia along the crescent curve of the Ganges River. Along its stone steps (ghats), the ancient rhythms of India play out in public: pilgrims perform dawn purifications, sadhus meditate beneath bamboo umbrellas, and smoke rises continuously from the burning steps of Manikarnika Ghat. Every evening at Dashashwamedh Ghat, the Ganga Aarti ritual fills the air with the scent of camphor and sandalwood, as priests wave massive brass lamps in synchronized movements to the accompaniment of bells and chants.',
    best_time: 'November to February', timings: 'Open all day · Aarti at sunrise & sunset',
    entry_fee: 'Free', map_link: 'https://maps.google.com/?q=Dashashwamedh+Ghat+Varanasi',
    nearby: ['Kashi Vishwanath Temple', 'Sarnath', 'Manikarnika Ghat'],
    trivia: 'Mark Twain once wrote: "Varanasi is older than history, older than tradition, older even than legend, and looks twice as old as all of them put together."',
    travel_tip: 'Hire a wooden rowboat at dawn (5:30 AM) from Assi Ghat to watch the morning rituals unfold from the water. Agree on the price before boarding.'
  },
  {
    slug: 'hawa-mahal', name: 'Hawa Mahal', state_slug: 'rajasthan', state_name: 'Rajasthan',
    city: 'Jaipur', category: 'Heritage', image_url: '/assets/place-hawamahal.jpg',
    tagline: 'A five-story screen of pink and red sandstone, designed as a cooling honeycomb of wind for the royal court.',
    description: 'Commissioned in 1799 by Maharaja Sawai Pratap Singh, the Hawa Mahal is a spectacular facade of pink-painted sandstone that resembles the crown of Krishna. Designed by Lal Chand Ustad, this architectural screen contains 953 intricate jharokhas (small latticed windows). It served a dual purpose: it allowed the women of the royal household to observe the busy street bazaars below without violating the strict rules of purdah, and it functioned as a natural air cooler, drawing air through its narrow vents to create a refreshing breeze throughout the palace chambers during Rajasthan\'s dry summers.',
    best_time: 'October to March', timings: '9:00 AM – 4:30 PM',
    entry_fee: '₹50 (Indian) · ₹200 (Foreign)', map_link: 'https://maps.google.com/?q=Hawa+Mahal+Jaipur',
    nearby: ['City Palace', 'Jantar Mantar', 'Amber Fort'],
    trivia: 'Hawa Mahal was built without a solid foundation. Because of its curved structure, it stands on its own, tilting slightly at a 87-degree angle.',
    travel_tip: 'The best view of the facade is actually from the rooftop cafes directly across the street. Grab a cup of local cardamom tea there at sunset.'
  },
  {
    slug: 'jaisalmer-fort', name: 'Jaisalmer Fort', state_slug: 'rajasthan', state_name: 'Rajasthan',
    city: 'Jaisalmer', category: 'Heritage', image_url: '/assets/place-jaisalmer.jpg',
    tagline: 'A medieval yellow sandstone fortress rising from the sands of the Thar, where families still inhabit centuries-old bastions.',
    description: "Rising from the flat expanse of the Thar Desert, Jaisalmer Fort is a medieval citadel carved entirely from yellow sandstone. Established in 1156 by Rawal Jaisal, it is one of the last remaining 'living' forts in the world: a quarter of the city's population still resides within its double-walled stone bastions, navigating narrow alleys lined with Havelis, ancient Jain temples, and quiet residential courtyards. At sunset, the golden sandstone absorbs the warm desert light, earning the fortress its name, Sonar Qila.",
    best_time: 'October to March', timings: '9:00 AM – 6:00 PM',
    entry_fee: '₹50 (Indian) · ₹250 (Foreign)', map_link: 'https://maps.google.com/?q=Jaisalmer+Fort',
    nearby: ['Patwon ki Haveli', 'Sam Sand Dunes', 'Gadisar Lake'],
    trivia: 'The fort is built without any mortar. The heavy sandstone blocks are fitted together using interlocking tongue-and-groove joints.',
    travel_tip: 'Wander deep into the fort\'s narrow lanes after 9:00 PM when the day-trippers leave. The illuminated sandstone walls look magical under the starry desert sky.'
  },
  {
    slug: 'alleppey-backwaters', name: 'Alleppey Backwaters', state_slug: 'kerala', state_name: 'Kerala',
    city: 'Alappuzha', category: 'Nature', image_url: '/assets/place-backwaters.jpg',
    tagline: 'A tranquil network of palm-shaded canals and shallow lakes traversed by traditional thatched-roof houseboats.',
    description: 'The backwaters of Alappuzha comprise a complex water network running parallel to the Malabar Coast. Here, village life revolves around narrow canals lined with coconut palms and low-lying paddy fields. Traveling through these waters on a kettuvallam—a traditional boat constructed from jackwood planks bound with coir rope without a single metal nail—reveals a slow-paced lifestyle of coir spinning, duck farming, and net fishing. The lake breezes and silent canals offer a quiet retreat from the coastal cities.',
    best_time: 'September to March', timings: 'Houseboats: 12:00 PM check-in',
    entry_fee: 'Houseboats from ₹8,000 / night', map_link: 'https://maps.google.com/?q=Alleppey+Backwaters',
    nearby: ['Marari Beach', 'Kumarakom Bird Sanctuary', 'Vembanad Lake'],
    trivia: 'The houseboats are built using traditional techniques without a single nail. The jackwood planks are tied together with coir ropes and sealed with caustic black resin.',
    travel_tip: 'Book a small country boat (shikhara) for a few hours in the afternoon to access the narrowest canals where the large houseboats cannot fit.'
  },
  {
    slug: 'munnar-tea-hills', name: 'Munnar Tea Hills', state_slug: 'kerala', state_name: 'Kerala',
    city: 'Munnar', category: 'Nature', image_url: '/assets/place-munnar.jpg',
    tagline: 'Manicured green tea bushes folding over the contours of the Western Ghats, wrapped in mountain mist.',
    description: 'Located in the Western Ghats at an elevation of 1,600 meters, Munnar is defined by its sprawling, manicured tea plantations that cover the undulating mountain slopes like a thick green carpet. The cool, damp climate and frequent mountain mists create ideal conditions for growing tea, a tradition started by British planters in the late 19th century. Beyond the tea estates, the hills rise to meet the peaks of Anamudi, offering habitats for endangered mountain goats, deep waterfalls, and dense forests.',
    best_time: 'September to May', timings: 'Estates open daylight hours',
    entry_fee: 'Tea Museum ₹150', map_link: 'https://maps.google.com/?q=Munnar+Kerala',
    nearby: ['Eravikulam National Park', 'Mattupetty Dam', 'Top Station'],
    trivia: 'The tea gardens of Munnar are home to the Neelakurinji flower, which blooms only once every twelve years, turning the hillsides a vibrant violet-blue.',
    travel_tip: 'Visit Lockhart Tea Factory (one of the oldest in the region) to taste fresh tea and watch the orthodox leaf-processing method first-hand.'
  },
  {
    slug: 'pangong-lake', name: 'Pangong Lake', state_slug: 'ladakh', state_name: 'Ladakh',
    city: 'Leh', category: 'Nature', image_url: '/assets/place-ladakh.jpg',
    tagline: 'A deep, high-altitude saltwater basin reflecting vivid shades of cobalt and turquoise against dry mountain cliffs.',
    description: 'Pangong Tso is a narrow, endorheic saltwater lake sitting at an altitude of 4,250 meters in the trans-Himalayan cold desert. Extending nearly 134 kilometers across the border from India into Tibet, the lake is surrounded by bare, multi-hued mountain ranges. Due to the high altitude and clean air, the water color shifts rapidly with the sun\'s position, transforming from a pale turquoise to deep cobalt. The stark landscape and clean alpine environment draw travelers to its desolate shores.',
    best_time: 'May to September', timings: 'Day visit recommended',
    entry_fee: 'Inner Line Permit required', map_link: 'https://maps.google.com/?q=Pangong+Tso+Lake',
    nearby: ['Nubra Valley', 'Hemis Monastery', 'Khardung La'],
    trivia: 'Despite being a saltwater lake, Pangong Tso freezes completely during the winter, allowing cars to be driven across its thick ice crust.',
    travel_tip: 'Due to the extreme altitude, spend at least 48 hours acclimatizing in Leh before traveling to Pangong to prevent acute mountain sickness.'
  },
  {
    slug: 'hampi-ruins', name: 'Hampi', state_slug: 'karnataka', state_name: 'Karnataka',
    city: 'Hampi', category: 'Heritage', image_url: '/assets/place-hampi.jpg',
    tagline: 'A vast valley of cracked granite boulders sheltering the stone ruins and columned temples of the Vijayanagara Empire.',
    description: 'Stretched across a dramatic river valley of giant granite boulders, Hampi preserves the ruins of the Vijayanagara Empire, which peaked in the 14th century. This UNESCO World Heritage site includes fortified royal enclosures, structured step-wells, and massive columned temple complexes like the Virupaksha Temple. The landscape is a mix of natural rock piles and ancient stone engineering, where historic market lanes and structural monuments tell of a wealthy trading center that once hosted merchants from Persia and Europe.',
    best_time: 'October to February', timings: 'Sunrise to sunset',
    entry_fee: '₹40 (Indian) · ₹600 (Foreign)', map_link: 'https://maps.google.com/?q=Hampi+Karnataka',
    nearby: ['Virupaksha Temple', 'Vittala Temple', 'Matanga Hill'],
    trivia: 'Hampi\'s Vittala Temple features 56 musical pillars. When gently tapped, these stone columns emit distinct musical notes of classical instruments.',
    travel_tip: 'Rent a bicycle or a moped to explore the vast ruins. Cross the Tungabhadra River in a circular coracle boat to visit the quieter \'hippie island\' side.'
  },
  {
    slug: 'mysore-palace', name: 'Mysore Palace', state_slug: 'karnataka', state_name: 'Karnataka',
    city: 'Mysuru', category: 'Heritage', image_url: '/assets/place-mysore.jpg',
    tagline: 'A grand royal palace blending Indo-Saracenic domes, stained glass, and rosewood carvings in Mysore.',
    description: 'Completed in 1912 as the seat of the Kingdom of Mysore\'s Wodeyar dynasty, this palace is a premier example of Indo-Saracenic architecture. The building combines elements of Rajput, Mughal, and Gothic styles, featuring grand domes, tall archways, and detailed stone columns. Inside, the Durbar Hall is decorated with stained-glass ceilings, mosaic floors, and hand-carved rosewood doors, reflecting the craftsmanship of the early 20th century.',
    best_time: 'October to March', timings: '10:00 AM – 5:30 PM',
    entry_fee: '₹70 (Indian) · ₹200 (Foreign)', map_link: 'https://maps.google.com/?q=Mysore+Palace',
    nearby: ['Chamundi Hills', 'Brindavan Gardens', "St. Philomena's Church"],
    trivia: 'Every Sunday evening and during the Dussehra festival, the palace is lit up by exactly 97,000 lightbulbs, drawing massive crowds to the lawns.',
    travel_tip: 'Visit the palace around 6:45 PM on a Sunday to watch the illumination happen all at once. Entry to the courtyard is free during this time.'
  },
  {
    slug: 'palolem-beach', name: 'Palolem Beach', state_slug: 'goa', state_name: 'Goa',
    city: 'Canacona', category: 'Beach', image_url: '/assets/place-goa.jpg',
    tagline: 'A sheltered crescent bay of golden sand and calm waters, lined with slanting coconut palms in South Goa.',
    description: 'Palolem Beach is a natural crescent bay situated in Canacona, South Goa. Protected by rocky headlands on both ends, the beach features calm, shallow waters suitable for swimming. Colorful wooden huts and local restaurants line the shore beneath coconut palms, offering a relaxed environment. The beach maintains a quieter atmosphere compared to the bustling, active resort areas of North Goa, making it popular for kayaking and coastal walks.',
    best_time: 'November to February', timings: 'Open all day',
    entry_fee: 'Free', map_link: 'https://maps.google.com/?q=Palolem+Beach+Goa',
    nearby: ['Cabo de Rama Fort', 'Butterfly Beach', 'Cotigao Sanctuary'],
    trivia: 'Just off the shore of Palolem lies Monkey Island, which can be reached by a short swim or kayak during low tide, offering panoramic sunset views.',
    travel_tip: 'Take a boat ride at 6:30 AM to spot wild dolphins playing in the bay, or enjoy a sunset paddleboard session when the waters are calm.'
  },
  {
    slug: 'rishikesh', name: 'Rishikesh', state_slug: 'uttarakhand', state_name: 'Uttarakhand',
    city: 'Rishikesh', category: 'Adventure', image_url: '/assets/place-rishikesh.jpg',
    tagline: 'A spiritual mountain sanctuary where the cold Ganges rushes past temple ashrams and high suspension bridges.',
    description: 'Located in the foothills of the Himalayas, Rishikesh is where the Ganges River leaves the mountains and enters the plains. The town is a long-standing spiritual center, filled with ashrams, meditation centers, and temples along the riverbank. Crossed by the massive suspension bridges of Ram Jhula and Lakshman Jhula, Rishikesh is also a hub for adventure sports, drawing visitors for river rafting and mountain trekking.',
    best_time: 'September to April', timings: 'Open all day',
    entry_fee: 'Free · activities priced separately', map_link: 'https://maps.google.com/?q=Rishikesh',
    nearby: ['Laxman Jhula', 'Triveni Ghat', 'Neelkanth Mahadev Temple'],
    trivia: 'Rishikesh gained global fame in 1968 when The Beatles visited the Maharishi Mahesh Yogi ashram to study Transcendental Meditation and wrote most of the White Album.',
    travel_tip: 'Walk across the suspension bridge of Ram Jhula at sunset to watch the river spark under the evening lights, and visit the Beatles Ashram ruins.'
  },
  {
    slug: 'meenakshi-temple', name: 'Meenakshi Amman Temple', state_slug: 'tamil-nadu', state_name: 'Tamil Nadu',
    city: 'Madurai', category: 'Religious', image_url: '/assets/place-meenakshi.jpg',
    tagline: 'A labyrinthine Dravidian temple complex topped by tall gateway towers covered in thousands of painted stone figures.',
    description: 'Dating back to the 6th century, the Meenakshi Amman Temple is the cultural core of Madurai. This Dravidian complex is enclosed by thick stone walls and features 14 gopurams (gateway towers) rising above the city. The towers are covered in over 33,000 stone and stucco sculptures of deities, mythical beasts, and historic characters. The interior contains the Hall of Thousand Pillars, a stone chamber supported by carved granite columns arranged in a grid.',
    best_time: 'October to March', timings: '5:00 AM – 12:30 PM · 4:00 PM – 10:00 PM',
    entry_fee: 'Free · Camera ₹50', map_link: 'https://maps.google.com/?q=Meenakshi+Amman+Temple+Madurai',
    nearby: ['Thirumalai Nayakkar Palace', 'Gandhi Memorial Museum', 'Alagar Hills'],
    trivia: 'The temple\'s Hall of Thousand Pillars features 985 uniquely carved granite columns, arranged in a grid pattern where they form a perfect alignment from any angle.',
    travel_tip: 'Dress conservatively (no shorts or sleeveless tops) and prepare to walk barefoot inside the temple. Non-Hindus are allowed in the courtyards but not the inner sanctums.'
  },
  {
    slug: 'mahabalipuram', name: 'Mamallapuram Shore Temple', state_slug: 'tamil-nadu', state_name: 'Tamil Nadu',
    city: 'Mamallapuram', category: 'Heritage', image_url: '/assets/place-mahabalipuram.jpg',
    tagline: 'An 8th-century granite temple built by the Pallava dynasty directly on the windswept shore of Mamallapuram.',
    description: 'Constructed in the 8th century under the Pallava ruler Rajasimha, the Shore Temple stands on the edge of the Bay of Bengal in Mamallapuram. Built of dressed granite blocks rather than carved from solid rock, it is one of the oldest structural stone temples in Southern India. The temple consists of two shrines dedicated to Shiva and one to Vishnu, withstanding centuries of ocean wind and salt spray, surrounded by carvings of couchant bulls.',
    best_time: 'November to February', timings: '6:00 AM – 6:00 PM',
    entry_fee: '₹40 (Indian) · ₹600 (Foreign)', map_link: 'https://maps.google.com/?q=Shore+Temple+Mamallapuram',
    nearby: ["Arjuna's Penance", 'Pancha Rathas', "Krishna's Butter Ball"],
    trivia: 'The temple survived the catastrophic 2004 Indian Ocean Tsunami. The receding water briefly exposed the ruins of the legendary "Seven Pagodas" offshore.',
    travel_tip: 'Visit late in the afternoon (4:30 PM). The soft golden light highlights the worn details of the granite carvings, and the sea breeze is refreshing.'
  },
  {
    slug: 'gateway-of-india', name: 'Gateway of India', state_slug: 'maharashtra', state_name: 'Maharashtra',
    city: 'Mumbai', category: 'Heritage', image_url: '/assets/place-gateway.jpg',
    tagline: 'A monumental basalt arch combining Roman design with traditional Gujarati stonework along Mumbai\'s harbor.',
    description: 'Completed in 1924 to commemorate the 1911 visit of King George V and Queen Mary, the Gateway of India stands along the waterfront at Apollo Bunder. This 26-meter-high archway is built of yellow basalt and features an Indo-Saracenic design that blends Roman triumphal arch architecture with local Gujarati stone-carving patterns. Facing the harbor, it has served historically as a welcoming point for ships arriving in Mumbai.',
    best_time: 'November to February', timings: 'Open 24 hours',
    entry_fee: 'Free', map_link: 'https://maps.google.com/?q=Gateway+of+India+Mumbai',
    nearby: ['Taj Mahal Palace Hotel', 'Elephanta Caves (ferry)', 'Colaba Causeway'],
    trivia: 'The Gateway is historically significant as the point from which the last British troops departed India on February 28, 1948, marking the end of colonial rule.',
    travel_tip: 'Take a morning ferry from the Gateway to the Elephanta Caves to get a spectacular view of the monument\'s arch from the water.'
  },
  {
    slug: 'ajanta-caves', name: 'Ajanta Caves', state_slug: 'maharashtra', state_name: 'Maharashtra',
    city: 'Aurangabad', category: 'Heritage', image_url: '/assets/place-ajanta.jpg',
    tagline: 'A sequence of 30 rock-cut Buddhist caves containing ancient frescoes painted on plaster in Aurangabad.',
    description: 'Carved into the basalt cliffs of a horseshoe-shaped gorge in Aurangabad, the Ajanta Caves comprise 30 rock-cut temples and monasteries dating from the 2nd century BCE to the 5th century CE. The caves are famous for preserving ancient Indian wall paintings, executed on mud plaster using natural earth pigments. These frescoes portray scenes from the Jataka tales, the life of the Buddha, and details of contemporary royal life, offering insights into early Indian art.',
    best_time: 'November to March', timings: '9:00 AM – 5:00 PM (closed Mondays)',
    entry_fee: '₹40 (Indian) · ₹600 (Foreign)', map_link: 'https://maps.google.com/?q=Ajanta+Caves',
    nearby: ['Ellora Caves', 'Daulatabad Fort', 'Bibi ka Maqbara'],
    trivia: 'The caves lay forgotten and swallowed by the jungle for over a thousand years until they were accidentally discovered in 1819 by a British officer, John Smith, during a tiger hunt.',
    travel_tip: 'Bring a small pocket flashlight (flash photography is prohibited). The guards will allow you to inspect the dark inner sanctuaries to appreciate the mural details.'
  },
  {
    slug: 'victoria-memorial', name: 'Victoria Memorial', state_slug: 'west-bengal', state_name: 'West Bengal',
    city: 'Kolkata', category: 'Heritage', image_url: '/assets/place-victoria.jpg',
    tagline: 'A grand white Makrana marble monument set in landscaped gardens in Kolkata.',
    description: 'Constructed between 1906 and 1921, the Victoria Memorial is a white Makrana marble building dedicated to the memory of Queen Victoria. The design blends British neoclassical structure with Mughal domes and Italian Renaissance details. Today, the monument houses a museum with galleries exhibiting historical paintings, manuscripts, and colonial artifacts, set within 64 acres of lawns, lakes, and gardens.',
    best_time: 'October to March', timings: '10:00 AM – 5:00 PM (closed Mondays)',
    entry_fee: '₹30 (Indian) · ₹500 (Foreign)', map_link: 'https://maps.google.com/?q=Victoria+Memorial+Kolkata',
    nearby: ['Indian Museum', "St. Paul's Cathedral", 'Maidan'],
    trivia: 'The bronze angel of victory on top of the central dome is mounted on large ball bearings and rotates with the wind.',
    travel_tip: 'Enjoy the light and sound show ("Pride & Glory") held in the gardens on winter evenings, which outlines the city\'s rich history.'
  },
  {
    slug: 'darjeeling', name: 'Darjeeling', state_slug: 'west-bengal', state_name: 'West Bengal',
    city: 'Darjeeling', category: 'Nature', image_url: '/assets/place-darjeeling.jpg',
    tagline: 'A high Himalayan ridge town surrounded by steep green tea estates with views of Mt. Kanchenjunga.',
    description: 'Sited at an elevation of 2,045 meters in the Lesser Himalayas, Darjeeling is known for its tea plantations and views of Mt. Kanchenjunga, the world\'s third-highest peak. The town grew as a sanatorium and hill station under British rule in the 19th century. It is home to the Darjeeling Himalayan Railway—a narrow-gauge steam line—and features a diverse population representing Tibetan, Nepali, and Bengali cultures, with a legacy of mountaineering.',
    best_time: 'March to May · September to November', timings: 'Open all day · Toy Train runs daily',
    entry_fee: 'Free · Toy Train Joy Ride ₹1,500', map_link: 'https://maps.google.com/?q=Darjeeling',
    nearby: ['Tiger Hill', 'Batasia Loop', 'Ghum Monastery'],
    trivia: 'Darjeeling tea is often referred to as the "Champagne of Teas" due to its delicate muscatel flavor, which cannot be replicated anywhere else.',
    travel_tip: 'Wake up at 4:00 AM and head to Tiger Hill to catch the sunrise. Watch the peak of Kanchenjunga light up in shades of orange and gold before the valleys do.'
  },
  {
    slug: 'shimla', name: 'Shimla', state_slug: 'himachal-pradesh', state_name: 'Himachal Pradesh',
    city: 'Shimla', category: 'Nature', image_url: '/assets/place-shimla.jpg',
    tagline: 'A mountain ridge town in the Himalayas with colonial-era timber buildings and cedar forests.',
    description: 'Shimla, located on the ridge of the foothills of the Himalayas, served as the summer capital of British India from 1864. The town\'s architecture includes prominent half-timbered Tudor-style buildings, such as the Viceregal Lodge and Christ Church. Today, the pedestrian Mall Road serves as the town center, surrounded by forests of Himalayan deodar cedars and pine trees.',
    best_time: 'March to June · December to January (snow)', timings: 'Open all day',
    entry_fee: 'Free', map_link: 'https://maps.google.com/?q=Shimla',
    nearby: ['Jakhoo Temple', 'Kufri', 'Viceregal Lodge'],
    trivia: 'The Kalka-Shimla toy train route crosses exactly 102 active tunnels and over 864 bridges as it climbs the mountain slopes.',
    travel_tip: 'Walk up the Jakhoo Temple trail (or take the ropeway) to the highest peak in Shimla to spot monkeys and enjoy panoramic mountain views.'
  },
  {
    slug: 'manali', name: 'Manali', state_slug: 'himachal-pradesh', state_name: 'Himachal Pradesh',
    city: 'Manali', category: 'Adventure', image_url: '/assets/place-manali.jpg',
    tagline: 'An alpine valley town on the Beas river, serving as a gateway to high-altitude Himalayan passes.',
    description: 'Manali lies in the valley of the Beas River, surrounded by pine forests, orchards, and high mountain peaks. The town acts as a popular base for outdoor trekking, mountaineering, and paragliding in the Solang Valley. Historically a quiet trade route, it now serves as the southern starting point of the key highway crossing high passes into the cold desert regions of Lahaul, Spiti, and Ladakh.',
    best_time: 'March to June · December to February', timings: 'Open all day',
    entry_fee: 'Free · activities priced separately', map_link: 'https://maps.google.com/?q=Manali',
    nearby: ['Solang Valley', 'Hadimba Temple', 'Rohtang Pass'],
    trivia: 'Old Manali is home to the wood-and-stone Hadimba Temple, built in 1553 around a natural cave where the goddess is said to have meditated.',
    travel_tip: 'Rent a mountain bike to explore the quiet pine paths of Old Manali, or drive through the Atal Tunnel to visit the stark valley of Lahaul.'
  },
];

module.exports = {
  states,
  places,
};
